# Generated by Django 3.2.6 on 2023-04-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='base_airport',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
