# Generated by Django 3.2.6 on 2023-04-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_airline_base_airport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aircraft',
        ),
    ]
